# Generated by Django 5.1.7 on 2025-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='describtion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
